# Generated by Django 2.2 on 2021-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nmid',
            field=models.IntegerField(db_index=True, default=None, unique=True),
            preserve_default=False,
        ),
    ]
