# Generated by Django 2.2 on 2021-01-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'todos',
                'verbose_name_plural': 'todoss',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
