# Generated by Django 2.2 on 2021-06-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_nmid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nmid',
        ),
    ]
